### PR TITLE
Watch: add comparing hashes of files

### PR DESCRIPTION
**Pull request by querielo**
Fixes https://github.com/playcanvas/playcanvas-sync/issues/49

Cc. @yaustar

### CODE REVIEW

**Review by willeastcott — APPROVED** [review]
LGTM. What do you think, @yaustar?

**Comment by yaustar** [comment]
Code looks fine. I would like to give it a test drive with some projects before merging though

**Comment by willeastcott** [comment]
OK, sounds good. I've leave it with you... 😄 
Thanks for the great contribution, @querielo!

**Comment by yaustar** [comment]
Had a look, because of the change in src/utils/local-contents.js, it means for every pushAll command, we are doing an extra hash call per file.

However, on my M1 Max this is taking 1ms on average per file to hash so this feels negligible. Even on a 5x slower machine with 300 files, this pushAll command would take an extra 1.5secs to do.

**Comment by querielo** [comment]
@yaustar  do you recommend something like [this](https://github.com/playcanvas/playcanvas-sync/pull/50/commits/b8842dba6cec00c82dd6ec22d76454c7dfab4641#diff-26cc2e4f9ac1fc6f51bcb97ee1867289364e3439b0706747f567b0e50e684f09R55)?

**Comment by yaustar** [comment]
> @yaustar what do you think about [this](https://github.com/playcanvas/playcanvas-sync/pull/50/commits/b8842dba6cec00c82dd6ec22d76454c7dfab4641#diff-26cc2e4f9ac1fc6f51bcb97ee1867289364e3439b0706747f567b0e50e684f09R55)?

Not sure what you mean by this 😅 

But when I looked at the hashing, I was using your branch and during a pushAll, it was doing that extra hash per file but benchmarking it, the time to hash files is fairly minimal, even for a large number of files.

**Comment by querielo** [comment]
Sorry to be not clear :-) I mean to remove md5 calculation from [local-contents.js](https://github.com/playcanvas/playcanvas-sync/pull/50/commits/b8842dba6cec00c82dd6ec22d76454c7dfab4641#diff-ce6b8fee0edf92fae5ebe2e63686ea09036ab9c0f47ccd0980818bf8b9fb906cL24) and [move it to the first iteration](https://github.com/playcanvas/playcanvas-sync/pull/50/commits/b8842dba6cec00c82dd6ec22d76454c7dfab4641#diff-26cc2e4f9ac1fc6f51bcb97ee1867289364e3439b0706747f567b0e50e684f09R57) of the watch loop.

**Comment by yaustar** [comment]
Oh, sorry. I didn't realise you made a new commit 😅  I re-review :)

**Pull request merged**
