### PR TITLE
Add method post

### PR DESCRIPTION
**Pull request by querielo**
It can be used as `await api.methodPost(PATH, PREF, true, payload);`

### CODE REVIEW

**Comment by yaustar** [comment]
For the purposes of a PR, I'm a bit hesitant to merge code that isn't used as it's quite confusing (why do we have an internal function that isn't used anywhere?) 

Do you have plans to use this function in a future PR? If so, I would prefer this to be merged with these changes so it's all in the same context.

**Comment by willeastcott** [comment]
@yaustar But aren't the functions in `api` for devs who want to programmatically drive pc-sync with Node? So I'm not sure it's right to say they're internal.

**Comment by yaustar** [comment]
> @yaustar But aren't the functions in `api` for devs who want to programmatically drive pc-sync with Node? So I'm not sure it's right to say they're internal.

Not really sure about the direction to go here as pc-sync wasn't meant to be a library to be built on top of programmatically.

We could change direction so that it is one and create a public API so that we have a default scripts to do things like push/pull etc

**Comment by querielo** [comment]
The main reason to use pc-sync as a library is ability to create a custom development pipeline with ESNext, Typescript, Eslint, Prettier, CI/CD, review processes and so on.

**Review by willeastcott — APPROVED** [review]

**Pull request merged**
